require("items.spaces")
-- require("items.apple")
require("items.front_app")
require("items.calendar")
-- require("items.uname")
require("items.volume")
require("items.battery")
require("items.network")
require("items.media")
